version: '3'

services:
  wordpress:
    image: wordpress:5.3-php7.3-fpm-alpine
    container_name: cms
    restart: always
    env_file: .env
    labels:
      - traefik.enable=false
    volumes:
      - wordpress:/var/www/html
  server-wordpress:
    image: nginx:1.17-alpine
    container_name: server-cms 
    restart: always
    ports:
      - "8000:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    labels:
        - traefik.frontend.rule=Host:www.${DOMAIN},${DOMAIN}
        - traefik.backend=website
        - traefik.port=80
volumes:
  wordpress:
